### ISSUE TITLE
Time log formatting

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [cruzang000/socialite#3]
@cruzang000 Nice job with the updates you made. Time Log formatting could be improved too, so that each entry appears on it's own line when viewed in GitHub. 

<img width="1680" alt="Screen Shot 2020-09-12 at 9 05 52 PM" src="https://user-images.githubusercontent.com/13874466/93008562-d134de80-f53b-11ea-993f-00d0b04af335.png">

**Comment by cruzang000** [comment]
ive added some mark up to the timelog.md file

**Comment by pawaitemadisoncollege** [comment]
That's looking better.  Are your user stories and screen design docs here somewhere?

**Comment by cruzang000** [comment]
i just pushed up my planning directory, they should be available in there now
