### ISSUE TITLE
project checkpoint 2 ready for review 

### ISSUE THREAD

**Issue by cruzang000** [cruzang000/socialite#5]
im ready for my checkpoint 2 review, i plan to convert those servlets into service classes as you suggested

**Comment by pawaitemadisoncollege** [comment]
You've made really good progress on your project so far @cruzang000, and Checkpoint 2 looks to be complete.

- [x] From looking at your entities, I think your db design is solid, but do you happen to have an easy-to-share erd of the database, so I can take a quick look? You can generate this right in intellij:   https://www.jetbrains.com/help/idea/creating-diagrams.html

**Comment by cruzang000** [comment]
I added a db diagram to the planning directory, it should be available now

**Comment by pawaitemadisoncollege** [comment]
Looks like a very solid design @cruzang000! You clearly put some good thought and time into it. Well done!
