### ISSUE TITLE
week 7 ready for review

### ISSUE THREAD

**Issue by cruzang000** [cruzang000/socialite#6]
week 7 is ready for review, i opted to implement form auth in my project

**Comment by pawaitemadisoncollege** [comment]
This looks good so far @cruzang000. 

As you continue adding functionality, remember to lock down the servlets and services that the member jsps and admin jsps use.  A savvy user may try to bypass the jsp and go directly to the service or servlet. 

- [x] there's an odd directory showing up:  
<img width="1680" alt="Screen Shot 2020-10-12 at 1 33 45 PM" src="https://user-images.githubusercontent.com/13874466/95779471-bdda7780-0c8f-11eb-832f-bc1fcc69e1e9.png">
 Carry over from windows?

**Comment by cruzang000** [comment]
yea it probably from windows, it should be gone now
