### ISSUE TITLE
Code Review @pawait

### ISSUE THREAD

**Issue by alisamoua** [cruzang000/socialite#7]
# Design/Code Review 1

### Reviewer: Alisa

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| I like the concept of the application.  It's will definitely draw users who are very sociable and enjoy the night life.  Have you thought about linking your app to Uber/Lyft? It would be cool for people to easily book a ride if they know they will be having too much fun! Also, it would be cool (stretch goal) if there was a way you were able to track the "traffic/how many people checked-in" to a certain place.  It would allow the user to either avoid or hit up a place where they know they can meet new people. I can't recall if you said users were able to have that option or not but just a thought! |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |The flow of your application is really nice and definitely easy for an everyday user to understand.  It's straight forward and to the point.  I can tell you put thought into your Design Doc as everything you listed is represented and displayed properly. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| The database flow here is pretty straight forward and was easy to follow along.  I don't really have any suggestions here as your table relationships all make sense. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. |Project structure looks great and was easy to follow along.  I don't have any suggestions here either as your code looks like its all in the right places. Did @paula 's search of "system.out.println" and you got NONE! NICE! Overall, great idea here and I'm excited to see the end product!|

@pawaitemadisoncollege

**Comment by cruzang000** [comment]
thanks Alisa!
