### ISSUE TITLE
Web Service Integration

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [cruzang000/socialite#9]
@cruzang000 First, great job working solidly ahead!  I like that you used properties right away here and have unit tests implemented too.

Just one area that I have question about:

- [ ] https://github.com/cruzang000/socialite/blob/efc1aaef43129674f2efaed6ef5157b8286909eb/src/main/java/edu/matc/entjava/socialite/persistence/GeoDao.java#L51-L60. Rather than manually parsing the json, what do you think about more automatically handling the mapping using ObjectMapper as shown here: http://paulawaite.com/education/java113/Module2/Week8/Activity3.html?

**Comment by cruzang000** [comment]
I attempted to use the Object Mapper, but it wasnt liking the excess fields in each json object and rather than ignore them it would throw an error, is there a way to avoid that? this specific section was probably the part I was questioning the most, the way I managed to do it now seems a bit rough

**Comment by pawaitemadisoncollege** [comment]
There are a few options, that you might check out:

- [x] objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false); 
- [ ] I think there is also an ignore annotation, but maybe that only for object to json and not the other way around...

**Comment by cruzang000** [comment]
ive implemented the object mapper in both of the api classes, all of the tests are passing and it is ready for a second review. At this point the GeoDao generates Search objects and persists, and the 
YelpDao generates Locations, LocationCategories, and LocationAddresses then persists as well.

**Comment by cruzang000** [comment]
hope this will also work as my week 8 exercise review
